import json
import hmac
import base64
import hashlib
import requests
from datetime import datetime, timezone

# --- 1. Fill in your OKX Dev Portal details here ---
API_KEY = "616b12fe-297f-4acf-aa49-3f7fe0c19bd5"
API_SECRET = "A9D9CD63D99CF03458ACBD50FD736731"
API_PASSPHRASE = "Oceanline_363"
CONTRACT_ADDRESS = "0x4B218726007858FC77fb2Aa476bd547d13f14670"
CONTRACT_NAME = "ParametricEscrow" 
# ---------------------------------------------------

# Read the JSON generated by Foundry
try:
    with open("standard-input.json", "r", encoding="utf-8") as f:
        source_code_json = f.read()
except FileNotFoundError:
    print("Error: standard-input.json not found. Run Step 1 first!")
    exit()

# Build the payload OKX expects
payload = {
    "chainShortName": "XLAYER",
    "contractAddress": CONTRACT_ADDRESS,
    "contractName": CONTRACT_NAME,
    "codeFormat": "solidity-standard-json-input",
    "sourceCode": source_code_json
}
body_str = json.dumps(payload, separators=(',', ':'))

# Generate the OKX signature
timestamp = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3] + 'Z'
request_path = "/api/v5/xlayer/contract/verify-source-code"
prehash_string = timestamp + "POST" + request_path + body_str

mac = hmac.new(bytes(API_SECRET, encoding='utf8'), bytes(prehash_string, encoding='utf-8'), digestmod=hashlib.sha256)
sign = base64.b64encode(mac.digest()).decode('utf-8')

# Send it
headers = {
    "Content-Type": "application/json",
    "OK-ACCESS-KEY": API_KEY,
    "OK-ACCESS-SIGN": sign,
    "OK-ACCESS-TIMESTAMP": timestamp,
    "OK-ACCESS-PASSPHRASE": API_PASSPHRASE
}

print("Transmitting to OKX...")
response = requests.post("https://web3.okx.com" + request_path, headers=headers, data=body_str)

print("\n--- OKX Response ---")
print(f"Status Code: {response.status_code}")
print(response.json())