// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./UnderwriterPool.sol";

/**
 * @title ParametricEscrow
 * @author Project Indemnify
 * @notice Core escrow engine managing the lifecycle of risk policies,
 * oracle settlements via bracketed risk matrices, and time-weighted premature termination.
 */
contract ParametricEscrow is ReentrancyGuard {
    using SafeERC20 for IERC20;

    // --- Custom Errors ---
    error ZeroAddress();
    error InvalidAsset();
    error PolicyNotActive();
    error PolicyAlreadySettled();
    error NotClient();
    error TimeoutReached();
    error InvalidSignature();
    error SignatureExpired();
    error InvalidTier();
    error OnlyOracle();
    error OnlyOwner();
    error SignatureAlreadyUsed();

    // --- Enums and Structs ---
    enum PolicyStatus {
        Active,
        Settled,    // Settled with Tier 0 (0% payout)
        Refunded,   // Client executed partial cashout
        Claimed     // Settled with Tiers 1, 2, or 3 (claim payout)
    }

    struct Policy {
        address clientAddress;
        address asset;
        uint256 coverageAmount;
        uint256 premiumPaid;
        uint256 startTimestamp;
        uint256 timeoutDuration;
        uint8 riskBracketTier;
        PolicyStatus status;
    }

    // --- Events ---
    event PolicyCreated(
        uint256 indexed policyId,
        address indexed client,
        address indexed asset,
        uint256 coverageAmount,
        uint256 premiumPaid,
        uint256 startTimestamp,
        uint256 timeoutDuration
    );
    event PolicySettled(
        uint256 indexed policyId,
        uint8 tier,
        uint256 payoutAmount,
        uint256 premiumTransferred
    );
    event PolicyTerminated(
        uint256 indexed policyId,
        uint256 refundAmount,
        uint256 underwriterFeeTransferred
    );
    event OracleAddressUpdated(address indexed oldOracle, address indexed newOracle);
    event PoolRegistered(address indexed asset, address indexed pool);
    event OwnershipTransferred(address indexed oldOwner, address indexed newOwner);

    // --- State Variables ---
    address public owner;
    address public oracleAddress;
    uint256 public policyCount;

    mapping(address => address) public assetToPool;
    mapping(uint256 => Policy) public policies;
    mapping(bytes32 => bool) public usedSignatures;

    // --- Modifiers ---
    modifier onlyOwner() {
        if (msg.sender != owner) revert OnlyOwner();
        _;
    }

    /**
     * @notice Constructor to initialize ParametricEscrow.
     * @param oracleAddress_ Address of the analytical oracle authorized to sign quotes and settle policies.
     */
    constructor(address oracleAddress_) {
        if (oracleAddress_ == address(0)) revert ZeroAddress();
        owner = msg.sender;
        oracleAddress = oracleAddress_;
        emit OwnershipTransferred(address(0), msg.sender);
    }

    // --- Administrative Functions ---

    /**
     * @notice Registers an UnderwriterPool for a specific stablecoin asset.
     * @param asset Address of the stablecoin (e.g. USDT/USDG).
     * @param pool Address of the corresponding UnderwriterPool.
     */
    function registerPool(address asset, address pool) external onlyOwner {
        if (asset == address(0) || pool == address(0)) revert ZeroAddress();
        assetToPool[asset] = pool;
        emit PoolRegistered(asset, pool);
    }

    /**
     * @notice Updates the oracle signature verification address.
     * @param newOracle Address of the new oracle.
     */
    function setOracleAddress(address newOracle) external onlyOwner {
        if (newOracle == address(0)) revert ZeroAddress();
        address oldOracle = oracleAddress;
        oracleAddress = newOracle;
        emit OracleAddressUpdated(oldOracle, newOracle);
    }

    /**
     * @notice Transfers ownership of the escrow contract.
     * @param newOwner Address of the new owner.
     */
    function transferOwnership(address newOwner) external onlyOwner {
        if (newOwner == address(0)) revert ZeroAddress();
        address oldOwner = owner;
        owner = newOwner;
        emit OwnershipTransferred(oldOwner, newOwner);
    }

    // --- Client Functions ---

    /**
     * @notice Creates an insurance policy using an off-chain cryptographic quote signature.
     * @param asset Address of the stablecoin asset.
     * @param coverageAmount Coverage amount requested by the client.
     * @param premiumAmount Premium quote generated by the analytical middleware.
     * @param timeoutDuration Duration of the timeout window before cashout is allowed.
     * @param deadline Expiration timestamp for the quote signature.
     * @param quoteId Unique identifier/nonce for the quote to prevent double-spend.
     * @param signature Cryptographic signature generated by the oracle.
     */
    function createPolicy(
        address asset,
        uint256 coverageAmount,
        uint256 premiumAmount,
        uint256 timeoutDuration,
        uint256 deadline,
        bytes32 quoteId,
        bytes calldata signature
    ) external nonReentrant returns (uint256 policyId) {
        if (block.timestamp > deadline) revert SignatureExpired();
        if (usedSignatures[quoteId]) revert SignatureAlreadyUsed();

        // Verify cryptographic quote signature
        bytes32 messageHash = keccak256(
            abi.encodePacked(
                msg.sender,
                asset,
                coverageAmount,
                premiumAmount,
                timeoutDuration,
                deadline,
                quoteId,
                block.chainid,
                address(this)
            )
        );
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);
        if (ECDSA.recover(ethSignedMessageHash, signature) != oracleAddress) revert InvalidSignature();

        address poolAddress = assetToPool[asset];
        if (poolAddress == address(0)) revert InvalidAsset();

        // Mark quote as consumed
        usedSignatures[quoteId] = true;

        // Pull the premium from client
        IERC20(asset).safeTransferFrom(msg.sender, address(this), premiumAmount);

        // Lock reserved capital inside the underwriter pool
        UnderwriterPool(poolAddress).lockCapital(coverageAmount);

        // Record policy config
        policyId = ++policyCount;
        policies[policyId] = Policy({
            clientAddress: msg.sender,
            asset: asset,
            coverageAmount: coverageAmount,
            premiumPaid: premiumAmount,
            startTimestamp: block.timestamp,
            timeoutDuration: timeoutDuration,
            riskBracketTier: 0,
            status: PolicyStatus.Active
        });

        emit PolicyCreated(
            policyId,
            msg.sender,
            asset,
            coverageAmount,
            premiumAmount,
            block.timestamp,
            timeoutDuration
        );
    }

    /**
     * @notice Allows a client agent to trigger premature termination of a stalled policy.
     * @dev Calculates a time-weighted pro-rata refund of the premium based on remaining block exposure,
     * releases all reserved capital back to the pool, and returns the underwriter fee to the pool.
     * @param policyId Unique ID of the active policy.
     */
    function terminatePolicy(uint256 policyId) external nonReentrant {
        Policy storage policy = policies[policyId];
        if (policy.status != PolicyStatus.Active) revert PolicyNotActive();
        if (msg.sender != policy.clientAddress) revert NotClient();

        uint256 elapsed = block.timestamp - policy.startTimestamp;
        if (elapsed >= policy.timeoutDuration) revert TimeoutReached();

        // Compute pro-rata refund and underwriter fee (multiplication before division)
        uint256 remaining = policy.timeoutDuration - elapsed;
        uint256 refundAmount = (policy.premiumPaid * remaining) / policy.timeoutDuration;
        uint256 underwriterFee = policy.premiumPaid - refundAmount;

        policy.status = PolicyStatus.Refunded;

        address poolAddress = assetToPool[policy.asset];
        
        // Release pool capital reservation
        UnderwriterPool(poolAddress).releaseCapital(policy.coverageAmount);

        // Refund client
        IERC20(policy.asset).safeTransfer(policy.clientAddress, refundAmount);

        // Route underwriter fee (earned premium) to pool base
        if (underwriterFee > 0) {
            IERC20(policy.asset).safeTransfer(poolAddress, underwriterFee);
        }

        emit PolicyTerminated(policyId, refundAmount, underwriterFee);
    }

    // --- Settlement Functions ---

    /**
     * @notice Directly settles a policy (Oracle-only push).
     * @param policyId Unique ID of the policy to resolve.
     * @param tier Resolved risk bracket tier (0, 1, 2, or 3).
     */
    function settlePolicy(uint256 policyId, uint8 tier) external {
        if (msg.sender != oracleAddress) revert OnlyOracle();
        _settlePolicy(policyId, tier);
    }

    /**
     * @notice Settles a policy by submitting a signed settlement proof (pull execution).
     * @param policyId Unique ID of the policy to resolve.
     * @param tier Resolved risk bracket tier (0, 1, 2, or 3).
     * @param signature Cryptographic signature of the settlement details signed by the oracle.
     */
    function settlePolicyWithSignature(
        uint256 policyId,
        uint8 tier,
        bytes calldata signature
    ) external nonReentrant {
        bytes32 messageHash = keccak256(
            abi.encodePacked(
                policyId,
                tier,
                block.chainid,
                address(this)
            )
        );
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);
        if (ECDSA.recover(ethSignedMessageHash, signature) != oracleAddress) revert InvalidSignature();

        _settlePolicy(policyId, tier);
    }

    // --- Internal Settlement Core ---

    /**
     * @dev Resolves capital allocation based on the non-binary parametric risk bracket.
     * Tier 0: Total Failure (Full Payout to Client)
     */
    function _settlePolicy(uint256 policyId, uint8 tier) internal {
        Policy storage policy = policies[policyId];
        if (policy.status != PolicyStatus.Active) revert PolicyNotActive();
        if (tier > 3) revert InvalidTier();

        policy.riskBracketTier = tier;

        address poolAddress = assetToPool[policy.asset];
        uint256 payoutAmount;

        if (tier == 0) {
            policy.status = PolicyStatus.Settled;
            // No payout, release reserved capital back to the pool
            UnderwriterPool(poolAddress).releaseCapital(policy.coverageAmount);
        } else {
            policy.status = PolicyStatus.Claimed;

            // Tier multipliers in basis points: Tier 1 (35%), Tier 2 (75%), Tier 3 (100%)
            uint256 bps = (tier == 1) ? 3500 : (tier == 2) ? 7500 : 10000;
            payoutAmount = (policy.coverageAmount * bps) / 10000;

            // Pay client and release remaining reserved capital
            UnderwriterPool(poolAddress).payout(policy.clientAddress, payoutAmount, policy.coverageAmount);
        }

        // Route 100% of premium paid directly to pool assets as yield
        IERC20(policy.asset).safeTransfer(poolAddress, policy.premiumPaid);

        emit PolicySettled(policyId, tier, payoutAmount, policy.premiumPaid);
    }
}
